<a href="https://colab.research.google.com/github/ShabnaIlmi/Data-Science-Group-Project/blob/recipe-risk-analyzer/DSGP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import LabelEncoder, StandardScaler


In [ ]:
# Load the dataset
file_path = "chemical_recipes_dataset.csv"  # Replace with the actual file path if necessary
data = pd.read_csv(file_path)

# Display the first few rows of the dataset
print(data.head())


  Recipe ID                                     Chemical Names  \
0    R-0001  Methylphosphonyl Difluoride + Chlorine + Hydro...   
1    R-0002        Sulfuric Acid + Methane + Hydrogen Peroxide   
2    R-0003  Potassium Cyanide + Methane + Ammonium Nitrate...   
3    R-0004                        Methane + Hydrogen Fluoride   
4    R-0005  Sulfuric Acid + Ethanol + Methane + Potassium ...   

                  Quantities  \
0         354g + 271g + 119g   
1          442g + 62g + 194g   
2  276g + 133g + 212g + 484g   
3                491g + 136g   
4   496g + 11g + 491g + 369g   

                                            Category  \
0                            Toxic Liquid, Toxic Gas   
1             Flammable Gas, Toxic Liquid, Explosive   
2   Flammable Gas, Toxic Solid, Explosive, Toxic Gas   
3                           Flammable Gas, Toxic Gas   
4  Flammable Gas, Toxic Solid, Toxic Liquid, Flam...   

                                  Potential Reaction Risk Level  
0  Pote

In [ ]:
# Encode the 'Risk Level' (target variable)
label_encoder = LabelEncoder()
data['Risk Level Encoded'] = label_encoder.fit_transform(data['Risk Level'])

# One-hot encode the 'Chemical Names' and 'Category'
chemical_dummies = data['Chemical Names'].str.get_dummies(sep=' + ')
category_dummies = data['Category'].str.get_dummies(sep=', ')

# Extract numerical values from 'Quantities' (sum the grams for simplicity)
data['Total Quantity (g)'] = data['Quantities'].str.extractall(r'(\d+)').astype(int).groupby(level=0).sum()

# Combine all features
X = pd.concat([chemical_dummies, category_dummies, data['Total Quantity (g)']], axis=1)
y = data['Risk Level Encoded']


In [ ]:
# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [ ]:
# Train a Random Forest Classifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

print("Model training complete.")


Model training complete.


In [ ]:
# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nAccuracy Score:", accuracy_score(y_test, y_pred))


Confusion Matrix:
[[114   0   0]
 [  0   0   1]
 [  0   0  85]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       114
           1       0.00      0.00      0.00         1
           2       0.99      1.00      0.99        85

    accuracy                           0.99       200
   macro avg       0.66      0.67      0.66       200
weighted avg       0.99      0.99      0.99       200


Accuracy Score: 0.995


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
import joblib

# Save the trained model to a file
joblib.dump(model, "risk_prediction_model.pkl")
print("Model saved as 'risk_prediction_model.pkl'")


Model saved as 'risk_prediction_model.pkl'


In [ ]:
# Example: Predict risk for a new chemical combination
new_data = pd.DataFrame({
    "Chemical Names": ["Ammonium Nitrate + Hydrogen Peroxide"],
    "Category": ["Explosive, Toxic Liquid"],
    "Quantities": ["200g + 100g"]
})

# Preprocess the new data
new_data['Total Quantity (g)'] = new_data['Quantities'].str.extractall(r'(\d+)').astype(int).groupby(level=0).sum()

# Create dummy features matching training data
chemical_features = pd.DataFrame(columns=chemical_dummies.columns)
category_features = pd.DataFrame(columns=category_dummies.columns)

# Fill in the matching dummy values
for col in chemical_features.columns:
    chemical_features.at[0, col] = 1 if col in new_data['Chemical Names'][0].split(" + ") else 0

for col in category_features.columns:
    category_features.at[0, col] = 1 if col in new_data['Category'][0].split(", ") else 0

# Combine all features
new_features = pd.concat([chemical_features, category_features], axis=1)
new_features['Total Quantity (g)'] = new_data['Total Quantity (g)']

# Fill missing columns with zeros to match training data
new_features = new_features.reindex(columns=X.columns, fill_value=0)

# Standardize
new_features_scaled = scaler.transform(new_features)

# Predict
predicted_risk = model.predict(new_features_scaled)
predicted_risk_label = label_encoder.inverse_transform(predicted_risk)

print("Predicted Risk Level:", predicted_risk_label[0])


Predicted Risk Level: High


In [ ]:
import joblib

# Save the trained scaler and label encoder
joblib.dump(scaler, "scaler.pkl")
joblib.dump(label_encoder, "label_encoder.pkl")


['label_encoder.pkl']

In [ ]:
import pandas as pd
import random
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Load the previously trained model and preprocessing objects
import joblib
model = joblib.load("risk_prediction_model.pkl")  # Load your trained model
scaler = joblib.load("scaler.pkl")  # Assuming you saved the scaler
label_encoder = joblib.load("label_encoder.pkl")  # Assuming you saved the label encoder

# Define function to process input chemicals and make prediction
def predict_chemical_risk(chemical_names, quantities, categories):
    # Creating the dataframe from the input
    input_data = pd.DataFrame({
        "Chemical Names": [chemical_names],
        "Quantities": [quantities],
        "Category": [categories]
    })

    # Extracting and summing the quantities
    input_data['Total Quantity (g)'] = input_data['Quantities'].str.extractall(r'(\d+)').astype(int).groupby(level=0).sum()

    # Creating feature columns for one-hot encoding
    chemical_features = pd.DataFrame(columns=chemical_dummies.columns)
    category_features = pd.DataFrame(columns=category_dummies.columns)

    # Fill the chemical features based on input data
    for col in chemical_features.columns:
        chemical_features.at[0, col] = 1 if col in chemical_names.split(" + ") else 0

    # Fill the category features based on input data
    for col in category_features.columns:
        category_features.at[0, col] = 1 if col in categories.split(", ") else 0

    # Combine the features
    new_features = pd.concat([chemical_features, category_features], axis=1)
    new_features['Total Quantity (g)'] = input_data['Total Quantity (g)']

    # Fill any missing columns from the training data
    new_features = new_features.reindex(columns=X.columns, fill_value=0)

    # Standardize the new data using the same scaler
    new_features_scaled = scaler.transform(new_features)

    # Predict risk
    predicted_risk = model.predict(new_features_scaled)
    predicted_risk_label = label_encoder.inverse_transform(predicted_risk)

    return predicted_risk_label[0]

# Example usage
chemical_input = input("Enter chemical names (separate by ' + '): ")
quantity_input = input("Enter quantities (separate by ' + '): ")
category_input = input("Enter categories (separate by ', '): ")

predicted_risk = predict_chemical_risk(chemical_input, quantity_input, category_input)

print("Predicted Risk Level:", predicted_risk)


Enter chemical names (separate by ' + '): Water +  Water
Enter quantities (separate by ' + '): 1000g + 2000g
Enter categories (separate by ', '): Explosive, Toxic Liquid
Predicted Risk Level: High
